### ISSUE TITLE
Can't compile the full project

### ISSUE THREAD

**Issue by AlexeyMarchenko** [pudabassman/Compiler_Maman16#1]
Hey, 
I'm trying to run this code with 
1.bison -d cpq.y
2.flex cpq.y

After comiplation the result is:
Visual Studio 2015 Error
Error	C2079	'id' uses undefined struct 'identifier'	
How did you solve it?
Thanks

**Comment by pudabassman** [comment]
Hey Alex,

First, Im still working on the project so don't expect it to work right
away.
Secondly, you compile the project by typing:
1. bison -d cpq.y
2. flex cpq.lex
3. gcc -o cpq.exe cpq.tab.c

Ami.
