### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by AlexeyMarchenko** [pudabassman/Compiler_Maman16#2]
Hey,
When I'm trying to run the code an segmentation fault appears.
The issue happens because of null pointer in 
DL_CONCAT(firstListsHead, secondListsHead); 
How did you fixed it?

**Comment by pudabassman** [comment]
Hey,

The code you are working with is fairly outdated. It depends on the input
file. You should read about Bison and Debugging with the -t option or you
can add a bunch of printf statements to follow the running code.

Ami.
